export const SET_CURRENT_ROUTE = 'SET_CURRENT_ROUTE';
export const ROUTES_FETCHING = 'ROUTES_FETCHING';
export const ROUTES_FETCH = 'ROUTES_FETCH';
export const SET_CURRENT_STOP = 'SET_CURRENT_STOP';
export const SET_DIRECTION = 'SET_DIRECTION';
